language: ruby
script: "./run-tests.sh"
cache: bundler
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - pip install --upgrade pip sphinx sphinx-autobuild sphinx_rtd_theme recommonmark --user
